In [1]:
'''
Neuron: Takes input signal(s), gives an output signal(s).

Activation Function: Value that is passed as output.
    * Threshold function (0 or 1)
    * Sigmoid function
    * Rectifier (zero until a point then activatives)
    * Hyperbolic Tangent (-1 to +1)


Input Layer: The inputs into the network.

Hidden Layer: Layers inbetween input/output to influence outputs.

Output Layer: Answers/Predicitons

Weights: Each neuron has a weight to its output.

Cost Function: Difference between result and desired result.

Backward Propergation: Difference between output and desired output and 
    feed difference back into network for weights to be adjusted.
    
Gradient Descent: Find the global minimum of the network.
    Think of a x^2 on a graph and finding the lowest point on y-axis.

Stochastic Gradient Descent: Find global minimum but avoid finding the local.
    minimum as there might be a lower point else where.

'''

'\nNeuron: Takes input signal(s), gives an output signal(s).\n\nActivation Function: Value that is passed as output.\n    * Threshold function (0 or 1)\n    * Sigmoid function\n    * Rectifier (zero until a point then activatives)\n    * Hyperbolic Tangent (-1 to +1)\n\n\nInput Layer: The inputs into the network.\n\nHidden Layer: Layers inbetween input/output to influence outputs.\n\nOutput Layer: Answers/Predicitons\n\nWeights: Each neuron has a weight to its output.\n\nCost Function: Difference between result and desired result.\n\nBackward Propergation: Difference between output and desired output and \n    feed difference back into network for weights to be adjusted.\n    \nGradient Descent: Find the global minimum of the network.\n    Think of a x^2 on a graph and finding the lowest point on y-axis.\n\nStochastic Gradient Descent: Find global minimum but avoid finding the local.\n    minimum as there might be a lower point else where.\n\n'

In [13]:
# Import librarys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import confusion_matrix


In [3]:
# Import the dataset
'''
Bank customers dataset. Why people are leaving the Bank for other Banks.
'''

root = '/Users/Haydn/Documents/Code/Jupyter/Machine Learning A-Z/1.0 - Example Data/Part 8 - Deep Learning/'
data_file = root + 'Artificial Neural Networks (ANN)/Churn_Modelling.csv'
dataset = pd.read_csv(data_file)
dataset

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

In [4]:
# Features and outcomes
x = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
x, y

(array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
        [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
        [502, 'France', 'Female', ..., 1, 0, 113931.57],
        ...,
        [709, 'France', 'Female', ..., 0, 1, 42085.58],
        [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
        [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object),
 array([1, 0, 1, ..., 1, 1, 0]))

In [5]:
# Encode the categorical data
label_encoder_1 = LabelEncoder()
label_encoder_2 = LabelEncoder()
x[:, 1] = label_encoder_1.fit_transform(x[:, 1]) # Country
x[:, 2] = label_encoder_2.fit_transform(x[:, 2]) # Gender

transformer_1 = ColumnTransformer([("country", OneHotEncoder(categories='auto'), [1])])
country_data = transformer_1.fit_transform(x)
transformer_2 = ColumnTransformer([("gender", OneHotEncoder(categories='auto'), [2])])
gender_data = transformer_2.fit_transform(x)

credit_score = x[:, [0]]
categorical_data = np.concatenate((country_data, gender_data), axis=1)
x = np.concatenate((credit_score, categorical_data, x[:, 3:]), axis=1)
x

array([[619, 1.0, 0.0, ..., 1, 1, 101348.88],
       [608, 0.0, 0.0, ..., 0, 1, 112542.58],
       [502, 1.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [709, 1.0, 0.0, ..., 0, 1, 42085.58],
       [772, 0.0, 1.0, ..., 1, 0, 92888.52],
       [792, 1.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [6]:
# Split test and train data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)

In [7]:
# Feature Scaling
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train

array([[ 0.16958176, -1.01460667, -0.5698444 , ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-2.30455945, -1.01460667,  1.75486502, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-1.19119591,  0.98560362, -0.5698444 , ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.9015152 ,  0.98560362, -0.5698444 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.62420521, -1.01460667, -0.5698444 , ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-0.28401079, -1.01460667,  1.75486502, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [8]:
# Make the ANN
model = Sequential()

In [9]:
# Adding some input and hiddern layers
# help(Dense)

# Layer 1
model.add(
    Dense(
        6, # number of neurons
        kernel_initializer='uniform', # random values for initialization
        activation='relu', # activation function
        input_dim=13,
    )
)

# Hidden layer
model.add(
    Dense(
        6, # number of neurons
        kernel_initializer='uniform', # random values for initialization
        activation='relu', # activation function
    )
)

In [10]:
# Output layer
model.add(
    Dense(
        1, # number of neurons
        kernel_initializer='uniform', # random values for initialization
        activation='sigmoid', # activation function
    )
)

In [11]:
# Complie
model.compile(
    optimizer='adam', # how to optimse the netwrok
    loss='binary_crossentropy', # loss function
    metrics=['accuracy'] # what we're interested in
)

In [12]:
# Fitting and training to the training data
model.fit(
    x_train, y_train,
    batch_size=10,
    epochs=100
)

Epoch 1/100
8000/8000 [==============================] - 2s 202us/step - loss: 0.4826 - acc: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.4288 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.4229 - acc: 0.7975
Epoch 4/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4193 - acc: 0.8224
Epoch 5/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.4165 - acc: 0.8265
Epoch 6/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4146 - acc: 0.8291
Epoch 7/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4134 - acc: 0.8315
Epoch 8/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.4123 - acc: 0.8316
Epoch 9/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4107 - acc: 0.8332
Epoch 10/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.4100 - acc: 0.8349

8000/8000 [==============================] - 1s 147us/step - loss: 0.3941 - acc: 0.8376
Epoch 83/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3929 - acc: 0.8359
Epoch 84/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.3936 - acc: 0.8372
Epoch 85/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3935 - acc: 0.8370
Epoch 86/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.3935 - acc: 0.8375
Epoch 87/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.3937 - acc: 0.8381
Epoch 88/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.3934 - acc: 0.8356
Epoch 89/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.3932 - acc: 0.8376
Epoch 90/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3935 - acc: 0.8366
Epoch 91/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3931 - acc: 0.8379
Epo

In [14]:
# Lets check resutls
y_predictions = model.predict(x_test)
y_predictions = (y_predictions > 0.5) # To get binary of left or stayed at Bank

In [16]:
# Lets see the results
cm = confusion_matrix(y_test, y_predictions)
cm

array([[1545,   50],
       [ 262,  143]])

In [19]:
'Accuracy', ((cm[0][0] + cm[1][1]) / 2000) * 100

('Accuracy', 84.39999999999999)