In [14]:
# Import libarys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [2]:
# Import the dataset
root = '/Users/Haydn/Documents/Code/Jupyter/Machine Learning A-Z/1.0 - Example Data/'
data_file = root + 'Part 2 - Regression/Multiple Linear Regression/50_Startups.csv'
dataset = pd.read_csv(data_file)
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [3]:
# Splitting features and outcomes
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1:].values

In [4]:
# Encode our categorical variables - State
encoder = LabelEncoder()
x[:, 3] = encoder.fit_transform(x[:, 3])
x

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [5]:
transformer = ColumnTransformer([("state", OneHotEncoder(categories='auto'), [3])])
split_data = transformer.fit_transform(x)
x = np.concatenate((x[:, :-1], split_data), axis=1) # As we get different array sizes back then drop column one and replace with new cols
x

array([[165349.2, 136897.8, 471784.1, 0.0, 0.0, 1.0],
       [162597.7, 151377.59, 443898.53, 1.0, 0.0, 0.0],
       [153441.51, 101145.55, 407934.54, 0.0, 1.0, 0.0],
       [144372.41, 118671.85, 383199.62, 0.0, 0.0, 1.0],
       [142107.34, 91391.77, 366168.42, 0.0, 1.0, 0.0],
       [131876.9, 99814.71, 362861.36, 0.0, 0.0, 1.0],
       [134615.46, 147198.87, 127716.82, 1.0, 0.0, 0.0],
       [130298.13, 145530.06, 323876.68, 0.0, 1.0, 0.0],
       [120542.52, 148718.95, 311613.29, 0.0, 0.0, 1.0],
       [123334.88, 108679.17, 304981.62, 1.0, 0.0, 0.0],
       [101913.08, 110594.11, 229160.95, 0.0, 1.0, 0.0],
       [100671.96, 91790.61, 249744.55, 1.0, 0.0, 0.0],
       [93863.75, 127320.38, 249839.44, 0.0, 1.0, 0.0],
       [91992.39, 135495.07, 252664.93, 1.0, 0.0, 0.0],
       [119943.24, 156547.42, 256512.92, 0.0, 1.0, 0.0],
       [114523.61, 122616.84, 261776.23, 0.0, 0.0, 1.0],
       [78013.11, 121597.55, 264346.06, 1.0, 0.0, 0.0],
       [94657.16, 145077.58, 282574.31, 0.

In [6]:
# Split dataset into train and test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
print('X Training Size: %s\n' % len(x_train), x_train, '\nX Test Size: %s\n' % len(x_test), x_test, '\nY Training Size: %s\n' % len(y_train), y_train, '\nY Test Size: %s\n' % len(y_test), y_test)

X Training Size: 40
 [[55493.95 103057.49 214634.81 0.0 1.0 0.0]
 [46014.02 85047.44 205517.64 0.0 0.0 1.0]
 [75328.87 144135.98 134050.07 0.0 1.0 0.0]
 [46426.07 157693.92 210797.67 1.0 0.0 0.0]
 [91749.16 114175.79 294919.57 0.0 1.0 0.0]
 [130298.13 145530.06 323876.68 0.0 1.0 0.0]
 [119943.24 156547.42 256512.92 0.0 1.0 0.0]
 [1000.23 124153.04 1903.93 0.0 0.0 1.0]
 [542.05 51743.15 0.0 0.0 0.0 1.0]
 [65605.48 153032.06 107138.38 0.0 0.0 1.0]
 [114523.61 122616.84 261776.23 0.0 0.0 1.0]
 [61994.48 115641.28 91131.24 0.0 1.0 0.0]
 [63408.86 129219.61 46085.25 1.0 0.0 0.0]
 [78013.11 121597.55 264346.06 1.0 0.0 0.0]
 [23640.93 96189.63 148001.11 1.0 0.0 0.0]
 [76253.86 113867.3 298664.47 1.0 0.0 0.0]
 [15505.73 127382.3 35534.17 0.0 0.0 1.0]
 [120542.52 148718.95 311613.29 0.0 0.0 1.0]
 [91992.39 135495.07 252664.93 1.0 0.0 0.0]
 [64664.71 139553.16 137962.62 1.0 0.0 0.0]
 [131876.9 99814.71 362861.36 0.0 0.0 1.0]
 [94657.16 145077.58 282574.31 0.0 0.0 1.0]
 [28754.33 118546.05 172795

In [7]:
# Fit the model
multi_linear_regression = LinearRegression().fit(x_train, y_train)

In [8]:
# Lets see how the model preforms with some test data
y_predications = multi_linear_regression.predict(x_test)

In [9]:
# How did it perform against the actual data.
print('Profit: Predications Vs Actual')
diff = y_predications - y_test
res = np.concatenate((y_predications, y_test, diff), axis=1)
print(res, '\n\nTotal Diff:', np.sum(diff))

Profit: Predications Vs Actual
[[103015.20159796 103282.38         -267.17840204]
 [132582.27760816 144259.4        -11677.12239184]
 [132447.73845174 146121.95       -13674.21154826]
 [ 71976.09851258  77798.83        -5822.73148742]
 [178537.48221055 191050.39       -12512.90778945]
 [116161.24230165 105008.31        11152.93230165]
 [ 67851.69209676  81229.06       -13377.36790324]
 [ 98791.73374687  97483.56         1308.17374687]
 [113969.43533012 110352.25         3617.18533012]
 [167921.0656955  166187.94         1733.1256955 ]] 

Total Diff: -39520.10244809772


In [11]:
# Backward Ellimination - Need to add a column of ones to make y = c + b1*x1 valid
x = np.append(np.ones((50, 1)).astype(int), x, axis=1)
x

array([[1, 165349.2, 136897.8, 471784.1, 0.0, 0.0, 1.0],
       [1, 162597.7, 151377.59, 443898.53, 1.0, 0.0, 0.0],
       [1, 153441.51, 101145.55, 407934.54, 0.0, 1.0, 0.0],
       [1, 144372.41, 118671.85, 383199.62, 0.0, 0.0, 1.0],
       [1, 142107.34, 91391.77, 366168.42, 0.0, 1.0, 0.0],
       [1, 131876.9, 99814.71, 362861.36, 0.0, 0.0, 1.0],
       [1, 134615.46, 147198.87, 127716.82, 1.0, 0.0, 0.0],
       [1, 130298.13, 145530.06, 323876.68, 0.0, 1.0, 0.0],
       [1, 120542.52, 148718.95, 311613.29, 0.0, 0.0, 1.0],
       [1, 123334.88, 108679.17, 304981.62, 1.0, 0.0, 0.0],
       [1, 101913.08, 110594.11, 229160.95, 0.0, 1.0, 0.0],
       [1, 100671.96, 91790.61, 249744.55, 1.0, 0.0, 0.0],
       [1, 93863.75, 127320.38, 249839.44, 0.0, 1.0, 0.0],
       [1, 91992.39, 135495.07, 252664.93, 1.0, 0.0, 0.0],
       [1, 119943.24, 156547.42, 256512.92, 0.0, 1.0, 0.0],
       [1, 114523.61, 122616.84, 261776.23, 0.0, 0.0, 1.0],
       [1, 78013.11, 121597.55, 264346.06, 1.0, 0.

In [22]:
# Create an optimal matrix of features - statistically significant to the profit.
# We want to find find features that are not important.
# These are features that have a P values > 0.5 (we can change 0.5 for experimentation)
x_optimal = x[:, [0, 1, 2, 3, 4, 5]] # basically features to examine...
x_optimal = np.array(x_optimal, dtype=float)
regressor_ols = sm.OLS(y, x_optimal).fit() # examine them...
regressor_ols.summary() # Lets look at the P values (x1, x2, x3..) - Lower the better

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Thu, 04 Jul 2019   Prob (F-statistic):           1.34e-27
Time:                        19:18:41   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.008e+04   6952.587      7.204      0.000    3.61e+04    6.41e+04
x1             0.8060      0.046     17.369      0.000       0.712       0.900
x2            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x3             0.0270      0.017      1.574      0.123      -0.008       0.062
x4            41.8870   3256.039      0.013      0.990   -6520.229    6604.003
x5           240.6758   3338.857      0.072      0.943   -6488.349    6969.701
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.47e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.47e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [23]:
# Lets remove the highest P values and retry. Feature 4.
x_optimal = x[:, [0, 1, 2, 3, 5]]
x_optimal = np.array(x_optimal, dtype=float)
regressor_ols = sm.OLS(y, x_optimal).fit() # examine them...
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Thu, 04 Jul 2019   Prob (F-statistic):           8.49e-29
Time:                        20:03:16   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.000    3.67e+04    6.35e+04
x1             0.8060      0.046     17.606      0.000       0.714       0.898
x2            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x3             0.0270      0.017      1.592      0.118      -0.007       0.061
x4           220.1585   2900.536      0.076      0.940   -5621.821    6062.138
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [24]:
# Lets remove the highest P values and retry. Feature 4.
x_optimal = x[:, [0, 1, 2, 3]]
x_optimal = np.array(x_optimal, dtype=float)
regressor_ols = sm.OLS(y, x_optimal).fit() # examine them...
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Thu, 04 Jul 2019   Prob (F-statistic):           4.53e-30
Time:                        20:04:22   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [25]:
# Lets remove the highest P values and retry. Feature 2.
x_optimal = x[:, [0, 1, 3]]
x_optimal = np.array(x_optimal, dtype=float)
regressor_ols = sm.OLS(y, x_optimal).fit() # examine them...
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Thu, 04 Jul 2019   Prob (F-statistic):           2.16e-31
Time:                        20:06:05   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [26]:
# So R&D spend and Marketing spend seem to be the best.
# But Marketing is 0.6 which is > 50%
x_optimal = x[:, [0, 1]]
x_optimal = np.array(x_optimal, dtype=float)
regressor_ols = sm.OLS(y, x_optimal).fit() # examine them...
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Thu, 04 Jul 2019   Prob (F-statistic):           3.50e-32
Time:                        20:09:07   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
# This suggests that R&D Spend is the highest statistical correclation
# to higher profits...